### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by hokagedemehin** [zuri-training/my-debtors-team32#18]
**Please describe the work you want to do**

Create the login page. of the project and also make it responsive on smaller screens

**Additional context**

![Screenshot 2022-07-28 153416](https://user-images.githubusercontent.com/16826624/181553808-cb809ebf-a8dc-4a7a-8430-08f6f610e4af.png)

**Comment by CatherineNjenga** [comment]
Working on this feature.
