### ISSUE TITLE
Create the Homepage

### ISSUE THREAD

**Issue by hokagedemehin** [zuri-training/my-debtors-team32#26]
**Please describe the work you want to do**

Create the landing page that everyone will see when they go to our web application.

**Additional context**

- Olokodana AbdulKabir @Olokoburnfire worked on the Homepage Navigation Bar, header and Footer using just Html, CSS and Javascript.
- Erica @ricaNga  worked on the Main content of the homepage using …

We created the navigation-bar, header and footer first then we moved on to the main content of the website. Lastly we made the the page Responsive.

![Landing pageteam32](https://user-images.githubusercontent.com/95130156/181908810-78f511b9-7d14-4981-911c-afb7665ed253.png)

**Comment by Olokoburnfire** [comment]
@hokagedemehin the homepage files has been uploaded.
