### ISSUE TITLE
Create "Add a Deptor Page" Hi-Fi Page

### ISSUE THREAD

**Issue by hokagedemehin** [zuri-training/my-debtors-team32#77]
**Please describe the work you want to do**

You will create the "add a debtor" page based on the new structure that will be in place.

## Project File
_**AddDebtorComp.jsx & addDebtor.css**_

**Additional context**

## Desktop Screen
![image](https://user-images.githubusercontent.com/16826624/183151919-9c04d049-ad32-4cd3-90e2-7a0351decca3.png)

## Mobile Screen
![image](https://user-images.githubusercontent.com/16826624/183154062-778bd037-b084-4280-92b8-6837c72fa009.png)

**Comment by CatherineNjenga** [comment]
Looks like the latest final work has updated the layout of this page.
